apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-bitrise-python-app
  labels:
    app: my-bitrise-python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-bitrise-python-app
  template:
    metadata:
      labels:
        app: my-bitrise-python-app
    spec:
      containers:
      - name: my-bitrise-python-app
        image: my-docker-repo/my-bitrise-python-app:latest  # Replace with your actual image
        command: ["sh", "-c", "git clone https://github.com/golemfatherof/dji.git && cd dji && pip install telebot flask aiogram pyTelegramBotAPI python-telegram-bot && chmod +x * && python3 raja.py"]  # Replace with your actual script path
        ports:
        - containerPort: 8080  # Adjust according to your app
        resources:
          limits:
            memory: "8000Mi"
            cpu: "8000m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: my-bitrise-python-app-service
spec:
  type: ClusterIP  # Change to LoadBalancer if you need external access
  selector:
    app: my-bitrise-python-app
  ports:
  - port: 80
    targetPort: 8080  # Port where the app is running
